Expose time-to-expire metric of Envoy authentication CA cert
racker/salus-telemetry-auth-service pull request #37
Opened 2020-09-18 14:23 UTC by shabd67

# Resolves

[SALUS-1029](https://jira.rax.io/browse/SALUS-1029)

# What

Expose time-to-expire metric of Envoy authentication CA cert

2020-09-18 20:30 UTC, itzg requested changes
Very good. Just needs the logging tweaks.

2020-09-18 20:30 UTC, itzg commented on src/main/java/com/rackspace/salus/authservice/services/VaultPKICACertExpirationMetric.java
> +        log.info("certificate to be expired after {} minutes ", diffInSeconds/1000 * 60 * 60);
This probably helped for development, but I think it can be deleted now.

2020-09-21 15:53 UTC, jjbuchan reviewed
One small suggestion for your error log.

I think the metric naming is fine.  The only thing I wondered is whether having `Seconds` at the end of the name would make it clearer what granularity the value is in... but I imagine the `unit` parameter will show up and provide that same goal.

2020-09-21 15:53 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/authservice/services/VaultPKICACertExpirationMetric.java
> +      log.error("error occurred reading certificates from vault "+e.getMessage());
```suggestion
      log.error("error occurred reading certificates from vault ", e);
```

I think I usually log errors like this. It allows you to get the full stacktrace in the log.  Looking at our code I see we do that a lot.

2020-09-21 15:55 UTC, itzg requested changes

2020-09-21 15:55 UTC, itzg commented on src/main/java/com/rackspace/salus/authservice/services/VaultPKICACertExpirationMetric.java
> +      log.error("error occurred reading certificates from vault "+e.getMessage());
Good catch. Yes, the exception/throwable must be listed as the last parameter, after placeholders (if any).

2020-09-22 13:12 UTC, itzg approved these changes

2020-09-22 14:43 UTC, jjbuchan approved these changes

2020-09-23 15:21 UTC, merged